<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9cca291a1a870d070765e343f2ec125d
{
    public static $prefixLengthsPsr4 = array (
        'B' => 
        array (
            'Bamarni\\Composer\\Bin\\' => 21,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Bamarni\\Composer\\Bin\\' => 
        array (
            0 => __DIR__ . '/..' . '/bamarni/composer-bin-plugin/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9cca291a1a870d070765e343f2ec125d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9cca291a1a870d070765e343f2ec125d::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit9cca291a1a870d070765e343f2ec125d::$classMap;

        }, null, ClassLoader::class);
    }
}
